import 'dotenv/config'
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { defineConfig } from 'prisma/config'

export default defineConfig({
  schema: 'src/infrastructure/prisma/schema.prisma',
  migrations: {
    path: 'src/infrastructure/prisma/migrations',
  },
  datasource: {
    url: `postgresql://${process.env.DB_USER}:${encodeURIComponent(process.env.DB_PASSWORD || '')}@${process.env.DB_HOST}:${process.env.DB_PORT}/${process.env.DB_NAME}?schema=public`,
  },
})
