import type { EditAttribute } from '../types/ldap'

export const DEFAULT_FETCH = [
  'dn',
  'sAMAccountName',
  'userPrincipalName',
  'cn',
  'mail',
  'memberOf',
  'telephoneNumber',
  'mobile',
  'description',
  'givenName',
  'sn',
  'displayName',
  'userAccountControl',
  'title',
  'department',
  'company',
  'physicalDeliveryOfficeName',
  'streetAddress',
  'l',
  'st',
  'co',
  'postalCode',
  'manager',
  'employeeID',
  'employeeNumber',
  'ipPhone',
  'wWWHomePage',
  'pwdLastSet',
  'whenCreated',
  'whenChanged',
  'objectClass',
] as const

export const DEFAULT_EDIT: EditAttribute[] = [
  { name: 'cn', label: 'Nome comum (cn)', section: 'Identidade' },
  { name: 'givenName', label: 'Nome (givenName)', section: 'Identidade' },
  { name: 'sn', label: 'Sobrenome (sn)', section: 'Identidade' },
  { name: 'displayName', label: 'Nome de exibição', section: 'Identidade' },
  { name: 'mail', label: 'E-mail', section: 'Contato' },
  { name: 'telephoneNumber', label: 'Telefone', section: 'Contato' },
  { name: 'mobile', label: 'Celular', section: 'Contato' },
  { name: 'description', label: 'Descrição', section: 'Contato' },
  { name: 'title', label: 'Cargo (title)', section: 'Organização' },
  { name: 'department', label: 'Departamento', section: 'Organização' },
  { name: 'company', label: 'Empresa (company)', section: 'Organização' },
  { name: 'physicalDeliveryOfficeName', label: 'Escritório / Local', section: 'Endereço' },
  { name: 'streetAddress', label: 'Endereço', section: 'Endereço' },
  { name: 'l', label: 'Cidade (l)', section: 'Endereço' },
  { name: 'st', label: 'Estado (st)', section: 'Endereço' },
  { name: 'co', label: 'País (co)', section: 'Endereço' },
  { name: 'postalCode', label: 'CEP', section: 'Endereço' },
  { name: 'employeeID', label: 'Matrícula (employeeID)', section: 'Outros' },
  { name: 'employeeNumber', label: 'Número do funcionário', section: 'Outros' },
  { name: 'ipPhone', label: 'Telefone IP', section: 'Outros' },
  { name: 'wWWHomePage', label: 'Página inicial (URL)', section: 'Outros' },
]
